--- 
- hosts: 172.31.81.147 
  become: yes 
  tasks: 
    - name: i want to install git 
      apt: 
       name: gittttt
       state: present 
      ignore_errors: yes
    
    - name: i want to install wget 
      apt: 
       name: wget 
       state: present 
   

    - name: i want to install tree 
      apt: 
       name: tree
       state: present 
      


