--- 
- hosts: 172.31.81.147  
  become: yes 
  tasks: 
   - name: install multi package 
     apt: 
      name: "{{ item }}" 
      state: present 
     loop: 
        - git 
        - wget 
        - tree
      
      
      